address: 3611
token: token
app_id: app_id
secret: secret
wechat_id: wechat_id
log_file: log/eatmyamway.log

prologue: Hi~ o(*￣▽￣*)ブ欢迎光临安利小卖部！\n小店共有安利[%d]枚，你已寄售安利[%d]枚~\n客官这是准备？\n0：被人安利\n1：安利别人
not_support: 请输入有效数字≧ ﹏ ≦
internal_error: 店小二失踪了，再试一次8~
not_found: 客官...8好意思...缺货了...请重新选择类型...(✿◡‿◡)