httpserver_address: :3611
wechat_token: token
wechat_app_id: app_id
wechat_secret: secret
wechat_id: wechat_id
wechat_interface: /interface/wechat
log_file: log/eatmyamway.log
database_driver: mysql
database_source: user:pass@(host:port)/database?charset=utf8mb4&parseTime=True&loc=Local
database_max_idle_conns: 10
database_max_open_conns: 100
database_conn_max_life_time: 3600000000000
default_amway_hp: 7
user_level_weight: 1
exp_publish_amway: 10
exp_interact_amway: 5
exp_somebody_like_my_amway: 1

internal_error: '|д･)...肥肠包芡，由于不明电波干扰，宁输入命令没有生效，请保持正确输入再试一次8~'
not_found: '|д･)...肥肠包芡，什么都没找到呢...康康其他的吧~'
not_support: '|д･)...肥肠包芡，这个功能还没开发，康康其他的吧...嘤嘤嘤'
default_nick_name: 友人A
publish_success: 发布安利成功~

amway_information: 招待不周~ 来自【%d】级用户【%s】UID:%d的安利！=͟͟͞͞ ٩( ๑╹ ꇴ╹)۶\n\n《%s》\n生命值：%d\n类型：%s\n安利理由：%s\n【伪】传送门：%s
node_subscribe: 久等了~%s感谢订阅【食我安利】！%so(*￣▽￣*)ブ%s鲁迅说：愿乐于分享的人都摆脱冷气，只是向人安利，不必听冷漠不屑者流的话。能安利的不吝啬，能接受的不拒绝。有一分热爱，分享一分喜欢，就令萤火一般，也可以在黑暗里发一点光，不必等候炬火。此后如竟没有炬火：我便是唯一的光。%sPS：和别人分享自己喜欢的事物，一份的快乐就能变成多份哟~%s
node_select_update_nick_name_or_dashboard: '那个~ 现在的昵称是：【%s】，要换个昵称吗？(๑• . •๑)\n1：好鸭...\n2：不了...'
node_update_nick_name: 那么~ 请输入新的昵称吧，不要超过8个字符哦~ (๑✦ˑ̫✦)
node_dashboard: 所以~ LV.%d【%s】大大，接下来做什么呢？(๑• . •๑)\n1：想被安利...\n2：我想安利...\n3：查看我的信息
node_select_interact_or_query_amway: 呐~ 喜欢这份安利吗？⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄\n\n1：喜欢...\n2：你是个好安利，可是...\n3：看看其他的...\n4：返回主界面
node_create_and_update_amway_name: 咳咳~ 想安利什么呢？不要超过20个字符哦~ (๑✦ˑ̫✦)\n1：返回
node_update_amway_type: 嗯嗯~ 这是番剧、游戏、视频、日剧美剧还是...呢？\n1：返回
node_select_update_amway_marketing_copy_or_skip: 好的知道了~ 宁为什么想安利它呢？(っ•̀ω•́)っ✎⁾⁾\n1：返回\n2：跳过
node_select_update_amway_fake_portal_or_skip: 这样啊~ 能不能给大家一个神奇链接呢~o(*≧▽≦)ツ\n1：返回\n2：跳过